apiVersion: v1
kind: ReplicationController
metadata:
  name: deep-web
  labels:
    name: deep-web
    deep: web
spec:
  replicas: 1
  selector:
    name: deep-web
  template:
    metadata:
      labels:
        name: deep-web
        deep: web
    spec:
      containers:
      - name: deep-web
        image: ipedrazas/deep-web
        ports:
        - containerPort: 8000
