apiVersion: v1
kind: Service
metadata:
  name: deep-reports-svc
  labels:
    name: deep-reports-svc
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    deep: reports
